import{a as m,S as g,i as y}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const h of s.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&n(h)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();const p="44822800-f7e5c6825510a03bf87da843b",L="https://pixabay.com/api/";async function u(t,r=1,i=15){const n={key:p,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:i};try{return(await m.get(L,{params:n})).data}catch{throw new Error("Error fetching images")}}function f(t){const r=document.querySelector(".gallery"),i=t.map(e=>`
    <a href="${e.largeImageURL}" class="gallery__link">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      <div class="info">
        <p class="info-item"><b>Likes</b>${e.likes}</p>
        <p class="info-item"><b>Views</b>${e.views}</p>
        <p class="info-item"><b>Comments</b>${e.comments}</p>
        <p class="info-item"><b>Downloads</b>${e.downloads}</p>
      </div>
    </a>
  `).join("");r.insertAdjacentHTML("beforeend",i),new g(".gallery a").refresh()}function b(){const t=document.querySelector(".gallery");t.innerHTML=""}function o(t,r="info"){y[r]({title:r==="error"?"Error":"Success",message:t,position:"topRight"})}let l="",d=1;const v=document.querySelector("#search-form"),c=document.querySelector(".load-more"),a=document.querySelector(".loader");v.addEventListener("submit",async t=>{if(t.preventDefault(),l=t.currentTarget.elements.searchQuery.value.trim(),!l){o("Please enter a search query","error");return}d=1,b(),c.classList.add("hidden");try{a.classList.remove("hidden");const r=await u(l,d);if(a.classList.add("hidden"),r.hits.length===0){o("Sorry, there are no images matching your search query. Please try again!","error");return}f(r.hits),r.hits.length===15&&c.classList.remove("hidden")}catch{a.classList.add("hidden"),o("Failed to fetch images. Please try again later.","error")}});c.addEventListener("click",async()=>{d+=1;try{a.classList.remove("hidden");const t=await u(l,d);if(a.classList.add("hidden"),t.hits.length===0){o("No more images available.","info"),c.classList.add("hidden");return}f(t.hits),t.hits.length<15&&(c.classList.add("hidden"),o("No more images available.","info")),w()}catch{a.classList.add("hidden"),o("Failed to fetch images. Please try again later.","error")}});function w(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
